image:
  repository: ghcr.io/miletocarmelo/dagster_successtest/pipeline-x
  tag: latest
  pullPolicy: Always  # Ajout recommandé pour les images :latest

environment: dev
module: pipeline-successtest

replicaCount: 1

grpc:
  port: 4000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  name: dagster-pipeline-successtest

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000

nodeSelector: {}

tolerations: []

affinity: {}
