apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "dagster-pipeline-successtest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dagster-pipeline-successtest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dagster-pipeline-successtest.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dagster-pipeline-successtest.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.grpc.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DAGSTER_HOME
              value: /opt/dagster/dagster_home
