apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-service
  labels:
    {{- include "dagster-pipeline-successtest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "dagster-pipeline-successtest.selectorLabels" . | nindent 4 }}
